window.PROJECTS = [
  {
    id: 'site',
    number: '01',
    title: 'TDN Studio',
    subtitle: 'Personal site / gateway',
    description: '整個內容與專案生態的入口，集中放置個人介紹、Blog、作品集與未來獨立工具的導覽。',
    category: '主網站',
    status: 'active',
    statusLabel: '目前使用中',
    tags: ['HTML', 'CSS', 'GitHub Pages'],
    href: '../index/',
    linkLabel: '查看主網站',
    accent: 'orange',
    featured: true,
  },
  {
    id: 'blog',
    number: '02',
    title: 'Blog / Field Notes',
    subtitle: 'Writing system / Markdown',
    description: '以 Markdown 為內容來源的多主題 Blog，記錄技術、地震與氣象觀察、專案開發與個人雜記。',
    category: '內容系統',
    status: 'building',
    statusLabel: '持續建置',
    tags: ['Markdown', 'JavaScript', 'Writing'],
    href: '../blog/',
    linkLabel: '閱讀 Blog',
    accent: 'coral',
    featured: true,
  },
  {
    id: 'editor',
    number: '03',
    title: 'Markdown Editor',
    subtitle: 'Local tool / Writing desk',
    description: '在本地編輯文章、即時預覽 Markdown、管理 front matter，並將圖片放入對應的文章資料夾。',
    category: '本地工具',
    status: 'building',
    statusLabel: '本地使用中',
    tags: ['Local only', 'File System API', 'Preview'],
    href: '../blog/editor/',
    linkLabel: '開啟編輯器',
    accent: 'ink',
    featured: false,
  },
  {
    id: 'api-docs',
    number: '04',
    title: 'API Docs',
    subtitle: 'Documentation / Future module',
    description: '未來可以獨立發布的 API 或技術文件入口，先保留在專案地圖裡，等內容成熟後再啟用。',
    category: '技術文件',
    status: 'planned',
    statusLabel: '規劃中',
    tags: ['Docs', 'Reference', 'Future'],
    href: '../api-docs/',
    linkLabel: '預留入口',
    accent: 'sage',
    featured: false,
  },
  {
    id: 'earth-weather',
    number: '05',
    title: 'Earth & Weather',
    subtitle: 'Observation / Data notes',
    description: '把地震與氣象觀察整理成可持續累積的資料、文章或工具，先從 Blog 的主題開始發展。',
    category: '觀察計畫',
    status: 'planned',
    statusLabel: '想法整理中',
    tags: ['Observation', 'Data', 'Taiwan'],
    href: '../blog/?category=earth-weather',
    linkLabel: '查看相關文章',
    accent: 'blue',
    featured: false,
  },
];
