window.BLOG_ARTICLES = [
  {
    id: '0001',
    slug: 'building-a-personal-site',
    title: '從一個空資料夾開始設計自己的網站',
    excerpt: '先把想留下來的東西整理清楚，再決定網站應該長什麼樣子。這是這個 Blog 的第一篇開發紀錄。',
    date: '2026-08-17',
    dateLabel: '2026.08.17',
    category: '專案紀錄',
    categoryKey: 'project',
    tags: ['網站', '設計', '專案紀錄'],
    readingTime: '6 min read',
    file: './posts/0001-building-a-personal-site.md',
    accent: 'orange',
    featured: true,
  },
  {
    id: '0002',
    slug: 'how-to-keep-field-notes',
    title: '如何把觀察、資料與直覺整理成一篇文章',
    excerpt: '文章不一定要從結論開始。從問題、資料和當下的疑問開始，也可以慢慢長成有用的紀錄。',
    date: '2026-08-11',
    dateLabel: '2026.08.11',
    category: '個人雜記',
    categoryKey: 'notes',
    tags: ['寫作', '觀察', '筆記'],
    readingTime: '4 min read',
    file: './posts/0002-how-to-keep-field-notes.md',
    accent: 'plum',
    featured: false,
  },
  {
    id: '0003',
    slug: 'earth-and-weather-records',
    title: '地震與氣象資料：我想留下什麼樣的紀錄',
    excerpt: '資料本身不會替我們說話，但好的整理方式能讓一次觀察在很久之後仍然被理解。',
    date: '2026-07-28',
    dateLabel: '2026.07.28',
    category: '地震／氣象',
    categoryKey: 'earth-weather',
    tags: ['地震', '氣象', '資料'],
    readingTime: '8 min read',
    file: './posts/0003-earth-and-weather-records.md',
    accent: 'olive',
    featured: false,
  },
];

window.BLOG_CATEGORIES = [
  { key: 'all', label: '全部文章' },
  { key: 'tech', label: '技術與工具' },
  { key: 'earth-weather', label: '地震／氣象' },
  { key: 'project', label: '專案紀錄' },
  { key: 'notes', label: '個人雜記' },
];
